export function scrollLogo() {
    for (let i = 0; i < 33; i++) {
        console.log('\n');
    }

    let lines = logo().split('\n');
    let delay = 100; // delay in milliseconds
    for (let i = 0; i < lines.length; i++) {
        setTimeout(function () {
            console.log(lines[i]);
        }, delay * i);
    }
}

export function logo() {
    return `     _____                                                                                                                                                      _____ 
    ( ___ )                                                                                                                                                    ( ___ )
     |   |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?77J5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7:~??^:JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPP55PPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPP7.7BBBG^.JPPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPP5555PPPPPPPPPPPPPPPPPPPP5555PPPPPPPPPPPPPPPPPPPPP555PPPPPPYJJYPPP?.!BBYPB5::YPP5JJJ5PPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP5|   | 
     |   |PPPP5PPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPP555PPPPPPJ^^!7^^7~:^GBG7JGBY:^!!:~!~:!5PPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP^.5BBG7!YPGBGGGGGGBGPJ~JBBB7.?GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP57:^PBBBBBGYJ?J5Y5Y??J5GBBBBBJ:^?PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7.?BBBGY5PYYY5PJ?JYPYYJ5PY5GBBB~.JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPJ:^5BBY7??7777?57J577777J?7PBGJ:^YPPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPG5^.5BP7JJJYYYYPJ55YYYYJY?JBB?.!PPPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPP5J?!:^GBG55YJ??775J5J77?JJY5PBBY.^7?Y5PPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?!^^~7J5GGGGG57?JJ?7YY5J7?J?7?PGGGGP5J7~^~7J5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5?~^~?5GBG5YJ7JYP5PPYYGPJ7?YGPYYG5PY5??JYPGBGY7~^~J5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPP55PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY~:~JGBB5J?JJJJYPYP!YGYYPP?7?YG5J5G?7PYPYJJJJ?YPBBP?^^75PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPP?.!PBBPJ7!?Y77JYP57G?77?JJ7J55?7J??77JG7G5Y?7J57!?YGBBY:^YPPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPP55PPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPP?.7BBP7!!?Y~YGBBBJ~5PPY?!!!YYYJ!!7J5PPJ^GBBGP?!57!!JBBP^:5PPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP7.!GBGJ7?^PBBBBBJ~7?GBGYJ??J??JJ5BBP77^PBBBBBJ~?7YBBP^:JPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP?.^PBBJ^5BBBBBBY~J~YGGJ7777!77?5GG?~?~GBBBBBB7~PBBY:^YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPY^:YBBGBBBBGBBB?P!!5PY?J??7?J?5PY~JYYBBGGBBBBGBG7.!5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPP55PPPPP5!.7GBBBB5GBBBGBY7PJ777777777755!PGGBBB5PGGBB5^:?PPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPJ:^YBBBY5GBBGG?JGY?77?JJ?77?5G75BBBBPY5GBG?.~YPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG5!:7GBBP5BGG5?7?Y5GPGGGGPG5Y7??GBBGYGBB5~:?PPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPYJJ??????JJ???????J55YJ???JJ???????JJ??JJ!.:JGBGGBB?Y?775BPBBBGGBJ77YJYBGGBBP7..7J?????JY5YJ?????????????????????????J5PPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPJ~^!7777777~!7777777~^^~!777!!7777777!!77777777YBBBBGJG5YJPBGGBBPBB5YYGPYBBBBY!!7?7777777!~:^!7777777777777777777777777!^~JPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPY.~GBBGGGGGBBBBGGGGGBBP5BBGGGBBBGGGGGBBBBGGGGGGGGGPPGPGPGGGPPGPPPGGGGGGGGGGGGBGBBGGGGGGGGGBGYPBBGGGGGGGGGGGGGGGGGBGGGGGBBP?:^JPPPPPPPPPPPPP|   | 
     |   |PPPPPP55PPPJ.!BBP::...^JGG^..::^?PBY~::.~JG!:.:::!5G^..?J..:P7:.:~~..P?:.:~~..5!..!5...557?GJ^.:^~:.JBG5GBG~:.:::.~P:..Y7..~P^:...^JGBG7.7PPPPPPPPPPPP|   | 
     |   |PPPP555PPPPP^:PBBJ: J7  !BJ. J?  ~Y  :P:  JJ. 75  .G~  JY  :B?. ?P:.~G?. ?G:.~G7  7G. .P5 :G5: ^G!  YGG7PBB7. J5: ~G:  5?  ~G?: ??  ~BBP:^PPPPPPPPP555|   | 
     |   |PPPPPPPPPPPP^:PBG:  5J  ~B^  5Y  ^Y  ^G^  J!  ?P  .G~  ?J  :B~  ?P!5BB!  ?GJPBB7  ~Y. .PG:!BJ  ~B!~!PBB7PBG.  5Y:7PG:  5?  ~G:  5Y  ^BBP:^PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  5J  ~B^  YJ  7Y  ^G^  J!  ~~.!YB~  :^  :G!  ::.5BB!  7B#BBBG57^^  .PBGGBJ  :?^. YBB7PBG:  ?J7BBG:  7?  ~B:  YY  ^BBP:^PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  ?^ !PB^  :. 7BY  ^G^  J!  :JGBBB~  JY  :B!  ~!!!~G!  ?BY!^GGJ~?G. .PBBBBJ .^7.  YBB7PBG:  . :GBG:   :  ~B:  YY  ^BBP:^PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  .!PBBB^  !?  !Y  ^G^  J!  ?#BBBB~  JY  :B!  JG. :G!  ?G  .G7  7G. .PBBBGY!~7B:  YBB7PBG:  777~7G:  !   ~B:  YY  ^BBP:^P5PPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  .!PBBB^  !?  !Y  ^G^  J!  ?#BBBB~  JY  :B!  JG. :G!  ?G  .G7  7G. .PBBBGY!~7B:  YBB7PBG:  777~7G:  !   ~B:  YY  ^BBP:^P5PPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  JBBBBB^  5Y  ^Y  ^G^  J!  ?BBBBB~  JY  :G~ :?7 .!G~ :77 .!G! :7?  ^PBGGGJ .7P:  YBB7PBG:  5Y  ^G:  57  ~B^  YY  ^BBP:^55PPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBP:  5BBBBB^  YY  ~Y  :P: .5~  7BBBBG~::JY^~!P?777????PYJJJJJJJPYJ???JPBBPGBBJ^^^^:~?GBG7GBG. ~5? :?G:  5?  ~B:  YY  ^BBP:^PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:GBG:  YBBBBB^  YJ  :P?^.:^?GB??J5BBGBBGBBBBBBBGGGGGGPPP55PPPPPPP55PPPPP5J!:7PGBBBBGBBBPJ^7BBP!~^^:..!P.  5?  ~B: :PY  ^BBP:^PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPP^:PBG:  YBBBBG:.:JJ!?JB#BGGBBGPGGP5Y7^!777!!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!?J~^~~~!!77!~^~^:?PPGBBBGGP5PJ7~J7. ^Y. ~?!  ~BB5.~PPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPY.~GBG. .JBBBBGPGBBBBGP5J7?7!~^~~~~~!7JJ??JJYYY55555PPPPPPPPPPPPPPPPPPPPPPPPPPP55YYJJJ?JY5PP?~~~~7??JY5PPBBBBGGP55Y?!^:~YGBB?.?PPPPPPPPPPPP|   | 
     |   |PPPPPP555PP?.7BBG5PGBBP?7JJ?7!~~~~~!???JY5PPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPP55PPPPPPPPPPPPPPPPPPPPPPPPPP55YYJ?77!!!~!7JY5PGBBBBBBGJ~^JPPPPPPPPPPPPP|   | 
     |   |PPPP555PPPP5!:!Y55J?!~^~77777?Y55PPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPP555PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP5YY?7!~~!!7777~~!J5PPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPY7!~~!7JY5PPPPPPPPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPP5PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP555YYY5PPPPPPPPPPPPPPPPP|   | 
     |   |PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP|   | 
     |   |55555555555555555555P55555555555555555555555P55555555555555555555555555555555555555555555Y55555555555555555555555Y55555555555555555555555Y555555555555|   | 
     |___|~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|___| 
    (_____)                                                                                                                                                    (_____)
    
    `;
}
